name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Atau branch lain yang Anda inginkan untuk memicu workflow ini

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Check out kode repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Langkah 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Langkah 3: Login ke Docker Hub (atau registry lainnya)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Langkah 4: Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t myusername/my-app:${{ github.sha }} .

    # Langkah 5: Push Docker Image ke Docker Hub
    - name: Push Docker image
      run: |
        docker push myusername/my-app:${{ github.sha }}
